### ISSUE TITLE
Tabcomplete Exeption on spawn command

### ISSUE THREAD

**Issue by TureBentzin** [TDRMinecraft/TDRStudios-Lobby-5#52]
[13:41:31] [Server thread/ERROR]: Exception when TDR_Minecraft attempted to tab complete spawn 1
org.bukkit.command.CommandException: Unhandled exception during tab completion for command '/spawn 1 ' in plugin TDRStudiosLobby5 v1.5
        at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:150) ~[spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at org.bukkit.command.Command.tabComplete(Command.java:93) ~[spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:231) ~[spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.tabCompleteCommand(CraftServer.java:1643) ~[spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.tabComplete(CraftServer.java:1615) ~[spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at org.bukkit.craftbukkit.v1_15_R1.command.BukkitCommandWrapper.getSuggestions(BukkitCommandWrapper.java:49) ~[spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:596) ~[spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:579) ~[spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:532) ~[spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.PacketPlayInTabComplete.a(SourceFile:35) ~[spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.PacketPlayInTabComplete.a(SourceFile:9) ~[spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
Caused by: java.lang.NullPointerException
        at de.tdrstudios.lobbyplugin.tabcomplete.TabComplete.onTabComplete(TabComplete.java:61) ~[?:?]
        at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:141) ~[spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        ... 22 more

**Comment by TureBentzin** [comment]
7838025266)
[14:15:33] [Server thread/ERROR]: Exception when TDR_Minecraft attempted to tab complete spawn
org.bukkit.command.CommandException: Unhandled exception during tab completion for command '/spawn ' in plugin TDRStudiosLobby5 v1.5
        at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:150) ~[spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at org.bukkit.command.Command.tabComplete(Command.java:93) ~[spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:231) ~[spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.tabCompleteCommand(CraftServer.java:1643) ~[spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.tabComplete(CraftServer.java:1615) ~[spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at org.bukkit.craftbukkit.v1_15_R1.command.BukkitCommandWrapper.getSuggestions(BukkitCommandWrapper.java:49) ~[spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:596) ~[spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:579) ~[spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:532) ~[spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.PacketPlayInTabComplete.a(SourceFile:35) ~[spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.PacketPlayInTabComplete.a(SourceFile:9) ~[spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
Caused by: java.lang.NullPointerException
        at de.tdrstudios.lobbyplugin.tabcomplete.TabComplete.onTabComplete(TabComplete.java:64) ~[?:?]
        at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:141) ~[spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
        ... 22 more
